"""
Django settings for command project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import environ
from django.contrib.messages import constants as message_constants
from django.contrib.messages import constants as messages
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")
MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')



LOG_PATH = os.path.join(BASE_DIR, 'server_logs')

if not os.path.join(LOG_PATH):
    os.mkdir(LOG_PATH)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,

    'formatters': {
        'standard': {'format': '[%(asctime)s %(levelname)s [%(funcName)s] [%(module)s:%(lineno)d] [%(process)d:%(threadName)s] %(message)s'},
        'normal': {'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s [%(funcName)s]'},
    },
    'handlers': {
        'null': {
            'level':'DEBUG' if DEBUG else 'WARNING',
            'class':'logging.NullHandler',
        },
        'logfile': {
            'level':'DEBUG' if DEBUG else 'WARNING',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_PATH,"Server_logs.log"),
            'maxBytes': 1024 * 1024 * 20, #Max 10MB
            'backupCount': 3,
            'formatter': 'standard',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter': 'standard',
            'class': 'logging.StreamHandler',
        },
        
         'restapis_allrequestslogs': {
            'level':'INFO',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_PATH,"restapis_allrequestslogs.log"),
            'maxBytes': 1024 * 1024 * 30, #Max 30MB
            'backupCount': 3,
            'formatter': 'standard',
        },
        
    },
    
    'loggers': {
        'django': {
            'handlers':['console'],
            'propagate': True,
            'level':'WARNING',
        },
        'django.request': {
            'handlers':['console'],
            'propagate': True,
            'level':'INFO',
        },
        
        '': {
            'handlers': ['console', 'logfile'],
            'level': 'INFO',
        },
        'restapis_allrequestslogs':{
            'handlers': ['restapis_allrequestslogs'], 
        },
    }
}
